… removed (commented out) all legacy project & dead unused code (still stack too deep error) 	- still received stack too deep error on compilation 		but not for any specific function 	- may need to start dividing up integration into other contract .sol files
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.